# Example configuration.yaml entry
automation:
  alias: Turn on light when sun sets
  trigger:
    platform: sun
    event: sunset
    offset: "-01:00:00"
  action:
    service: light.turn_on

automation 2:
  alias: Turn on TV at 5PM
  trigger:
    platform: time
    after: '17:00:00'
  action:
    service: switch.turn_on
    entity_id: switch.harmony_hub_1
